# Site settings
title: Isabeau Lewis

header_pages:
  - research.md
  - illustration.md
  - gallery.md
  - cv.md
  
navigation:
- text: Research
  internal: true
  url: ./research.md
- text: Illustration
  internal: true
  url: ./illustration.md
- text: Gallery
  internal: true
  url: ./gallery.md
- text: CV
  internal: true
  url: ./cv.md
