# Site settings
title: Isabeau Lewis
author: 
  name: Isabeau Lewis
  email: 18iml@queensu.ca

# Build settings
remote_theme: jekyll/minima

header_pages:
  - research.md
  - illustration.md
  - gallery.md
  - cv.md
