# Site settings
title: Isabeau Lewis
author: 
  name: Isabeau Lewis
description: Loving plants, evolution, and plant evolution.

# Build settings
remote_theme: jekyll/minima

header_pages:
  - research.md
  - illustration.md
  - gallery.md
  - cv.md
